function clear_axis(app)

cla(app.ax_msna_raw)
cla(app.ax_burst_interval_his)
cla(app.ax_burst_duration_his)
cla(app.ax_burst_amplitude_his)
cla(app.ax_burst_integral_his)
cla(app.ax_burst_res)
cla(app.ax_msna_int)
cla(app.ax_1st_phase)
cla(app.ax_last_hist)
cla(app.ax_all_hist)
yyaxis(app.ax_spike_msna, 'left')
cla(app.ax_spike_msna)
yyaxis(app.ax_spike_msna, 'right')
cla(app.ax_spike_msna)
cla(app.ax_last_phase)
cla(app.ax_last_shape)
cla(app.ax_all_phase)
cla(app.ax_all_shape)
cla(app.ax_1st_shape)
cla(app.ax_1st_hist)
cla(app.ax_cluster_timestamps)
cla(app.ax_cluster_shapes)
cla(app.ax_spect_1_1)
cla(app.ax_spect_2_1)
cla(app.ax_spect_3_1)
cla(app.ax_spect_4_1)
cla(app.ax_spect_1_2)
cla(app.ax_spect_2_2)
cla(app.ax_spect_3_2)
cla(app.ax_spect_4_2)
cla(app.ax_signal)
cla(app.ax_wavelet_sig1)
cla(app.ax_xwt3)
cla(app.ax_wavelet_sig2)
cla(app.ax_xwt2)
cla(app.ax_xwt1)
cla(app.ax_wave_signals)
cla(app.ax_entropy3)
cla(app.ax_entropy2)
cla(app.ax_entropy1 )
cla(app.ax_entropy4)
cla(app.ax_signals_corre)
cla(app.ax_signal1_corre)
cla(app.ax_signal2_corre)
cla(app.ax_corre_1_1_1)
cla(app.ax_corre_1_1_2)
cla(app.ax_corre_1_2_1)
cla(app.ax_corre_1_2_2)
cla(app.ax_corre_2_1_1)
cla(app.ax_corre_2_1_2)
cla(app.ax_corre_2_2_1)
cla(app.ax_corre_2_2_2)
cla(app.ax_corre_3_1_1)
cla(app.ax_corre_3_1_2)
cla(app.ax_corre_3_2_1)
cla(app.ax_corre_3_2_2)
cla(app.ax_regression2)
cla(app.ax_regression1)
cla(app.ax_annotate_1_1)
cla(app.ax_annotate_2_1)
cla(app.ax_annotate_3_1)
cla(app.ax_annotate_4_1)
cla(app.ax_annotate_1_2)
cla(app.ax_annotate_2_2)
cla(app.ax_annotate_3_2)
cla(app.ax_annotate_4_2)
cla(app.ax_spike_shape)
cla(app.ax_trans_1_1)
cla(app.ax_trans_1_2)
cla(app.ax_trans_1_3)
cla(app.ax_trans_2_1)
cla(app.ax_trans_2_2)
cla(app.ax_trans_2_3)





